pipeline {

    agent any

    stages{
        stage('Build App Image') {
          steps {
            script {
              sh """
                docker build .  -t omarkorety/movieapp:V${BUILD_NUMBER}
                echo ${BUILD_NUMBER}
                docker login -u ${USERNAME} -p ${PASSWORD}
                docker push omarkorety/movieapp:V${BUILD_NUMBER}
                echo ${BUILD_NUMBER} > ../build_num.txt
                """
                    }
                        } 
                }
            }


        stage('Upload Image'){
          steps{

            }
          }
        }

        
    }




//                                 export BUILD_NUMBER=\$(cat ../build_num.txt)
//                                 mv Deployment/deploy.yaml Deployment/deploy.yaml.tmp
//                                 cat Deployment/deploy.yaml.tmp | envsubst > Deployment/deploy.yaml
//                                 rm -f Deployment/deploy.yaml.tmp
//                                kubectl apply -f Deployment -n jenkins